### ISSUE TITLE
Contao 4.9.19 - Redirect settings are not shown

### ISSUE THREAD

**Issue by Webstylerin** [heimrichhannot/contao-loginredirects-bundle#4] opened 2021-08-19 16:11 UTC
I use this extension with Contao for a few weeks. In the meantime I updated to 4.9.19, all works fine.

Now I have 2 new sites, currently also 4.9.19, but in both sites "Redirects" is empty, the widget-part is missing.

Under access protection I can see the member groups. I can't tell any difference between the old working and the new installations.

Any suggestions? What did I miss?

Regards
Nicole
![2021-08-19 18-07-56](https://user-images.githubusercontent.com/3033160/130103728-d552b3a3-8347-4cfb-9b0a-f085cbe205bc.png)
![2021-08-19 18-09-08](https://user-images.githubusercontent.com/3033160/130103952-d39678fa-d9b7-4309-9b84-e2a097bc7521.png)

**Comment by Defcon0** [comment] 2021-09-01 11:44
Fixed in latest version. The cause was a missing dependency. Thanks for reporting :-)!

**Closed as completed by Defcon0** 2021-09-01 11:44 UTC

**Comment by Webstylerin** [comment] 2021-09-01 13:41
Thanks @Defcon0 for fixing. Theoreticaly I can add redirects now, but there is a SQL-error.

With the install-tool a column was droped after updating.

`An exception occurred while executing 'UPDATE tl_content SET `lr_choose_redirect`='a:1:{i:0;a:2:{s:5:\"lr_id\";s:10:\"allmembers\";s:14:\"lr_redirecturl\";s:24:\"{{link_url::42|urlattr}}\";}}' WHERE id='277'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lr_choose_redirect' in 'field list'`

**Comment by Defcon0** [comment] 2021-09-01 13:48
Please update your database ;-)

**Comment by Webstylerin** [comment] 2021-09-01 14:09
Well I did update the database via install-tool but it droped the column:

`ALTER TABLE tl_content DROP lr_choose_redirect`

![Bildschirmfoto 2021-09-01 um 16 05 39](https://user-images.githubusercontent.com/3033160/131686221-bc599fc9-2c75-41c1-b992-8b0f29260466.png)

**Comment by Defcon0** [comment] 2021-09-01 14:49
You're right, missed that one. It's fixed in the latest version 1.0.5.
